# Generated by Django 5.1.4 on 2024-12-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('pik', 'Pik'), ('kier', 'Kier'), ('karo', 'Karo'), ('trefl', 'Trefl')], max_length=10)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('markings', models.CharField(blank=True, choices=[('walet', 'Walet'), ('dama', 'Dama'), ('krol', 'Król'), ('as', 'As')], max_length=10, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
