# Generated by Django 5.1.4 on 2024-12-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='markings',
            new_name='marking',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
    ]
