# Generated by Django 5.1.4 on 2025-01-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_rename_markings_card_marking_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_hand',
            field=models.ManyToManyField(related_name='player_hand', to='game.card'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_hand', models.ManyToManyField(related_name='computer_hand', to='game.card')),
                ('deck', models.ManyToManyField(related_name='deck', to='game.card')),
                ('last_played_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_played', to='game.card')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='game.player')),
            ],
        ),
    ]
