# Generated by Django 5.1.4 on 2025-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_player_hand_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_hand',
        ),
        migrations.AddField(
            model_name='game',
            name='player_hand',
            field=models.ManyToManyField(related_name='player_hand', to='game.card'),
        ),
    ]
