# Generated by Django 5.1.4 on 2025-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_player_hand_game_player_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discard_pile',
            field=models.ManyToManyField(related_name='discard_pile', to='game.card'),
        ),
    ]
