# Generated by Django 5.1.4 on 2025-01-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_card_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_opponent', to='game.player'),
        ),
    ]
