# Generated by Django 5.1.4 on 2025-01-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_hand',
            field=models.ManyToManyField(blank=True, related_name='opponent_cards', to='game.card'),
        ),
    ]
