# Generated by Django 5.1.4 on 2025-01-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_opponent_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
