# Generated by Django 5.1.4 on 2025-01-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('player', 'Gracz'), ('opponent', 'Przeciwnik')], default='player', max_length=10),
        ),
    ]
