# Generated by Django 5.1.4 on 2025-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_action_done',
            field=models.BooleanField(default=False),
        ),
    ]
