# Generated by Django 5.1.4 on 2025-02-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_turn_action_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('started', models.BooleanField(default=False)),
                ('deck', models.ManyToManyField(related_name='multiplayer_deck', to='game.card')),
                ('discard_pile', models.ManyToManyField(related_name='multiplayer_discard_pile', to='game.card')),
                ('players', models.ManyToManyField(related_name='multiplayer_games', to='game.player')),
                ('turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='rooms', to='game.player')),
            ],
        ),
    ]
